server:
  servlet:
    encoding:
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: localhost
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  token:
    secret: "secretKey"
